<a href="https://colab.research.google.com/github/peter-kiilu/python_course/blob/main/Numpy_Class_Practises_Morning_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np


In [ ]:
# Numpy as a Numerical Compuation Library: Linear Algebra(matrices & vectors), Calculus, Statistical

# OBJECTIVES:
# a) Understand numpy arrays (ndarrays) and thier properties
# b) Create a numpy array using built-in functions in numpy: Data Mining
# c) Index and Slice information from a numpy array: Data Extraction
# d) Mathematical and Statistical process in a numpy: Data Manipulation
# e) Reshape and Transpose Data in a Numpy array: Data Tranformation

In [ ]:
# CREATING A NUMPY ARRAY
# Using np.array(list, tuple, range()), we can convert these sequence datatypes to numpy arrays

# 1. List
student_marks = [89, 56, 67, 90, 45]
print(type(student_marks))

# Converting a python list to a numpy array
import numpy as np
student_marks_array = np.array(student_marks)
print(type(student_marks_array))


# 2. Tuple
student_marks = (89, 56, 67, 90, 45)
print(type(student_marks))

student_marks_array = np.array(student_marks)
print(type(student_marks_array))


# 3. range()
student_reg_numbers = range(1001, 1006)
print(type(student_reg_numbers))

student_reg_numbers_array = np.array(student_reg_numbers)
print(type(student_reg_numbers_array))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'range'>
<class 'numpy.ndarray'>


In [ ]:
# 1D Array
# NB: A numpy array can only store values of the same DataType(Homogenous)
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Properties

print(arr1.shape)  # Shape of the array
print(arr1.ndim)   # Number of dimensions
print(arr1.size)   # Total number of elements
print(arr1.dtype)  # Data type of elements

[1 2 3 4 5]
(5,)
1
5
int64


In [ ]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

print('=========')

print(arr2.shape)  # Shape of the array(The Number of Rows and Columns)
print(arr2.ndim)   # Number of dimensions
print(arr2.size)   # Total number of elements
print(arr2.dtype)  # Data type of elements

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [ ]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

print('=========')

print(arr3.shape)  # Shape of the array(The Number of Rows and Columns)
print(arr3.ndim)   # Number of dimensions
print(arr3.size)   # Total number of elements
print(arr3.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
8
int64


In [ ]:
# Creating Numpy Arrays using Built-in Functions
# a) np.ones() and np.zeros(): Creates an array with zeros and ones as float datatype
np.ones((3,3))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# b) Identity Matrix
identity_matrix = np.eye(3)  # 4x4 Identity matrix
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# c) Using random arrays
# i) As Floats
rand_array = np.random.rand(3, 3)  # Random values between 0 and 1: Flaot64 By Default
rand_array

# ii) As Integers
rand_ints = np.random.randint(1, 20, (3, 3))  # Random integers
rand_ints

array([[16, 14, 13],
       [11, 16, 12],
       [18,  4,  4]])

In [ ]:
# d) Sequences
# i) np.arange(start, stop, step)
range_array = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
range_array

# ii) np.linspace()
linspace_array = np.linspace(0, 100, 5)  # [0, 2.5, 5, 7.5, 10]
linspace_array

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# Objective 3: Indexing and Slicing Numpy Arrays
# Extract information stored in a Numpy Array

# i) Indexing a 1D Array
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])    # Accessing element at index 1 (20)
print(arr[-1])   # Accessing last element (50)

# Slicing 1D Array
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Accessing elements from index 1 to 3 (20, 30, 40)


20
50
[20 30 40]


In [ ]:
# ii) Indexing and Slicing 2D Array
# 2D -> (rows, columns)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

print('===========')

print(arr2d[0, :])  # First row

print('============')

print(arr2d[:, 1])  # Second column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[2 5 8]


In [ ]:
# Objective 4: Mathematical and Statistical Operation
# i) Mathematical
arr = np.array([1, 2, 3, 4])
print(arr + 2)  # [3 4 5 6]
print(arr * 2)  # [2 4 6 8]

print('============')

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5 7 9]

[3 4 5 6]
[2 4 6 8]
[5 7 9]


In [ ]:
# ii) Statistical
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))  # Mean
print(np.median(arr))  # Median
print(np.std(arr))  # Standard deviation
print(np.var(arr))  # Variance
print(np.sum(arr))  # Sum
print(np.min(arr))  # Minimum
print(np.max(arr))  # Maximum
print(np.sort(arr))  # Sort


3.0
3.0
1.4142135623730951
2.0
15
1
5
[1 2 3 4 5]


In [ ]:
# Objective 5: Reshaping and Transposing
# i) Reshaping: Rearranging the Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print('========')

reshaped = arr.reshape(3, 2)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# ii) Transposing: Converting row as columns and vice versa
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print('========')

transposed = arr.T
print(transposed)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
